# Generated by Django 5.0.14 on 2026-03-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('register_user', 'Register User'), ('register_vendor', 'Register Vendor'), ('password_reset', 'Password Reset'), ('admin_login', 'Admin Login')], max_length=32),
        ),
    ]
