# Generated by Django 5.0.14 on 2026-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
