# Generated by Django 5.0.14 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_market_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapcategory",
            name="icon",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
